Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using WepPha2.Models;
using Microsoft.AspNetCore.Identity;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using QuestPDF.Previewer;
using WepPha2.ViewModels;
using System.ComponentModel;
using WepPha2.Interfaces;
using WepPha2.Models.DocumentModels;

namespace WepPha2.Controllers
{
    public class ReportController : Controller
    {
        private readonly IMedicineRepository _medicineRepository;
        private readonly IPurchaseRepository _purchaseRepository;
        private readonly IEmployeeRepository _employeeRepository;
        
        public ReportController(IMedicineRepository medicineRepository, 
            IPurchaseRepository purchaseRepository,
            IEmployeeRepository employeeRepository)
        {
            _medicineRepository = medicineRepository;
            _purchaseRepository = purchaseRepository;
            _employeeRepository = employeeRepository;
        }

        // Conventional route - handled by default route
        public IActionResult Index()
        {
            return View();
        }

        // Attribute route with optional parameter and default value
        [Route("Reports/Medicine/{format?}")]
        public async Task<IActionResult> CreateMedicineReport(string format = "pdf") 
        {
            var medicines = await _medicineRepository.GetAll();  
            var document = new InvoiceMedicineDocument(medicines);
            var pdfBytes = document.GeneratePdf();
            string nameOfFile = $"MedicineReport{DateTime.Now}.pdf";
            return File(pdfBytes, "application/pdf", nameOfFile);
        }

        public async Task<IActionResult> CreatePurchaseReport()
        {
            var purchases = await _purchaseRepository.GetAll();
            var document = new InvoisePurchaseDocument(purchases);
            var pdfBytes = document.GeneratePdf();
            string nameOfFile = $"PurchaseReport{DateTime.Now}.pdf";
            return File(pdfBytes, "application/pdf", nameOfFile);
        }

        public async Task<IActionResult> CreateEmployeeReport()
        {
            var employees = await _employeeRepository.GetAll();
            var document = new InvoiceEmployeeDocument(employees);
            var pdfBytes = document.GeneratePdf();
            string nameOfFile = $"EmployeeReport{DateTime.Now}.pdf";
            return File(pdfBytes, "application/pdf", nameOfFile);
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.AccessControl;
using WepPha2.Data;
using WepPha2.Interfaces;
using WepPha2.Models;
using WepPha2.Repository;
using WepPha2.Services;
using WepPha2.ViewModels;

namespace WepPha2.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly UserManager<AppUser> _userManager;
        private readonly IEmployeeRepository _employeeRepository;
        public UserController(IUserRepository userRepository, UserManager<AppUser> userManager, IEmployeeRepository employeeRepository)
        {
            _userRepository = userRepository;
            _userManager = userManager;
            _employeeRepository = employeeRepository;
        }

        //[HttpGet("users")]
        
        public async Task<IActionResult> Index()
        {
            var users = await _userRepository.GetAllUsers();
            List<UserViewModel> result = new List<UserViewModel>();
            foreach (var user in users)
            {
                var userViewModel = new UserViewModel()
                {
                    Id = user.Id,
                    Email = user.UserName,
                    Phone = user.PhoneNumber
                };
                result.Add(userViewModel);
            }
            return View(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditProfile(string id)
        {
            var user = await _userRepository.GetUserById(id);

            if (user == null)
            {
                return View("Error");
            }

            var editMV = new EditProfileViewModel()
            {
               Id =user.Id,
               Email = user.Email,
               Phone = user.PhoneNumber,
               UserName = user.Email
            };
            return View(editMV);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditProfile(EditProfileViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditProfile", editVM);
            }

            var user2 = await _userRepository.GetUserById(editVM.Id);
            string email = user2.Email; 
            if (user2 == null)
                return View("Error");

            var roles = await _userManager.GetRolesAsync(user2);

            user2.UserName = editVM.UserName;
            user2.PhoneNumber = editVM.Phone;
            user2.Email = editVM.Email;

            if (roles.FirstOrDefault() == "user")
            {
                await _employeeRepository.UpdateUserEmployee(user2,email);
            }       
            await _userManager.UpdateAsync(user2);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(string id)
        {
            var userDetails = await _userRepository.GetUserById(id);
            if (userDetails == null) return View("Error");
            return View(userDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var userDetails = await _userRepository.GetUserById(id);

            if (userDetails == null)
            {
                return View("Error");
            }
            _userRepository.Delete(userDetails);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> CreateUserEmployee()
        {
            ViewBag.EmployeeList = await _userRepository.GetAllEmployee();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUserEmployee(CreateUserEmployeeViewModel UserVM)
        {
            ViewBag.EmployeeList = await _userRepository.GetAllEmployee();
            var employer = await _userRepository.GetEmployeeById(UserVM.EmployeId);
            
            if (ModelState.IsValid)
            {
                //return View(medicine);
                var user = await _userManager.FindByEmailAsync(employer.Email);
                if (user != null)
                {
                    TempData["Error"] = "This email address is already in use";
                    return View(UserVM);
                }

                var newUser = new AppUser()
                {
                    Email = employer.Email,
                    UserName = employer.Email,
                    PhoneNumber = employer.Phone

                };
                var newUserResponse = await _userManager.CreateAsync(newUser, UserVM.Password);

                if (newUserResponse.Succeeded)
                    await _userManager.AddToRoleAsync(newUser, UserRoles.User);
              

                return RedirectToAction("Index");
            }

            return View();

        }
        public async Task<IActionResult> CreateUserAdmin()
        {
            ViewBag.EmployeeList = await _userRepository.GetAllEmployee();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUserAdmin(CreateAdminUserViewModel UserVM)
        {
            if (ModelState.IsValid)
            {
                //return View(medicine);
                var user = await _userManager.FindByEmailAsync(UserVM.Email);
                if (user != null)
                {
                    TempData["Error"] = "This email address is already in use";
                    return View(UserVM);
                }

                var newUser = new AppUser()
                {
                    Email = UserVM.Email,
                    UserName = UserVM.Email,
                };
                var newUserResponse = await _userManager.CreateAsync(newUser, UserVM.Password);

                if (newUserResponse.Succeeded)
                    await _userManager.AddToRoleAsync(newUser, UserRoles.Admin);


                return RedirectToAction("Index");
            }

            return View();

        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@{
    var currentUser = await UserManager.GetUserAsync(User);
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pharmacy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel="stylesheet" href="~/css/style_nav_bar.css" asp-append-version="true" />
    
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        @if (User.Identity.IsAuthenticated )
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Medicine" asp-action="Index">Medicines</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Purchase" asp-action="Index">Purchases</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Pharmacy" asp-action="Index">Pharmases</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Notification" asp-action="Index">Notify System</a>
                            </li>

                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                                </li> 
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="LogOut">Log out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>