Models/PurchaseDetails.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WepPha2.Models
{
    public class PurchaseDetails
    {
        [Key]
        public int PurchaseDetailId { get; set; }
        [ForeignKey("Medicine")]
        public int PurchasedMedicineId { get; set; }
        public Medicine? PurchasedMedicine { get; set; }
        public int Count { get; set; }

        [ForeignKey("Purchase")]
        public int PurchaseId { get; set; }

    }
}

Controllers/PurchaseDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations.Schema;
using WepPha2.Interfaces;
using WepPha2.Models;
using WepPha2.Repository;
using WepPha2.Services;
using WepPha2.ViewModels;

namespace WepPha2.Controllers
{
    public class PurchaseDetailsController : Controller
    {
        private readonly IPurchaseDetailsRepository _purchaseDetailsRepository;
        private readonly IMedicineRepository _medicineRepository;

        public const string CartSessionKey = "CartId";
        public PurchaseDetailsController(IPurchaseDetailsRepository purchaseDetailsRepository, IMedicineRepository medicineRepository)
        {
            _purchaseDetailsRepository = purchaseDetailsRepository;
            _medicineRepository = medicineRepository;
        }
        public async Task<IActionResult> Details(int id)
        {
            var medicinesByIdPurchase = await _purchaseDetailsRepository.GetMedicinesByPurchaseId(id);
            return View(medicinesByIdPurchase);
        }

        public IActionResult AddToPurchase(int id, int count)
        {
            var cart = GetCart() ?? new Dictionary<int, int>();
            if (!cart.ContainsKey(id))
            {
                cart[id] = count;
                SaveCart(cart);
            }

            return RedirectToAction("Index", "Medicine");
        }

        private Dictionary<int, int>? GetCart()
        {
            var cart = Request.Cookies[CartSessionKey];
            return cart == null
                ? new Dictionary<int, int>()
                : JsonConvert.DeserializeObject<Dictionary<int, int>>(cart);
        }
        public IActionResult ViewCart()
        {
            var cart = GetCart() ?? new Dictionary<int, int>();
            return View(cart);
        }
        public IActionResult CleanCart()
        {
            Response.Cookies.Delete(CartSessionKey);
            return RedirectToAction("Index","Purchase");
        }

        private void SaveCart(Dictionary<int, int> cart)
        {
            var cartJson = JsonConvert.SerializeObject(cart);
            Response.Cookies.Append(CartSessionKey, cartJson);
        }
        public async Task<IActionResult> Create(int id)
        {          
            var cart = GetCart() ?? new Dictionary<int, int>();
            foreach (var item in cart)
            {     
                var purchasedmedicine = await _medicineRepository.GetMedicineById(item.Key);
                
                var purchaseDetails = new PurchaseDetails
                {
                    PurchasedMedicineId = item.Key,
                    Count = item.Value,
                    PurchaseId = id,
                    PurchasedMedicine =  purchasedmedicine
                };
                _purchaseDetailsRepository.Add(purchaseDetails);
                purchasedmedicine.Quantity = purchasedmedicine.Quantity - item.Value;
                _medicineRepository.Update(purchasedmedicine);
            }
            Response.Cookies.Delete(CartSessionKey);
            
            return RedirectToAction("Index", "Purchase");

        }
        public IActionResult DeleteFromCart(int id)
        {
            var cart = GetCart() ?? new Dictionary<int, int>();
            cart.Remove(id);
            SaveCart(cart);
            return RedirectToAction("ViewCart");
        }
        public async Task<IActionResult> UpdateCount(int itemId, int count)
        {
            var medicine = await _medicineRepository.GetMedicineById(itemId);
            if (count < medicine.Quantity)
            {
                var cart = GetCart() ?? new Dictionary<int, int>();
                cart[itemId] = count;
                SaveCart(cart);
                return RedirectToAction("ViewCart");
            }
            else
            {
                //return RedirectToAction("Error");
                return Problem();
            }

        }
    }
}

Views/PurchaseDetails/Details.cshtml
@model IEnumerable<WepPha2.Models.PurchaseDetails>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/css/style_nav_bar.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <h2>Details of purchase</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Purchase ID</th>
                    <th>Count</th>
                    <th>Medicine Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PurchaseId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Count)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PurchasedMedicine.MedicineName)
                        </td>                       
                    </tr>                   
                }
               
            </tbody>
        </table>
    </div>
</body>
</html>

Views/PurchaseDetails/ViewCart.cshtml
@using WepPha2.Interfaces;
@using WepPha2.Repository;
@using WepPha2.ViewModels
@model Dictionary<int,int>

@inject IMedicineRepository medrep

@{
    var medicineDetails = await medrep.GetMedicineDetails(@Model);
    var finalPrice = medicineDetails.Sum(details => details.TotalPrice);
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/css/style_nav_bar.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <h2>Cart List</h2>
        <ul class="list-group">
            @for(int i =0; i< @Model.Count; i++)
            {
                <form asp-controller="PurchaseDetails" asp-action="UpdateCount" method="post">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <strong>ID:</strong>  @Model.ElementAt(i).Key
                    </div>
                    <div>
                   
                        <div>
                            <strong>Name:</strong> @medicineDetails[i].Name
                        </div>
                        <div>
                            <strong>Price:</strong> @medicineDetails[i].BasePrice
                        </div>
                        <div>
                            <strong>Total Price:</strong> @medicineDetails[i].TotalPrice
                        </div>
                        
                    </div>
                    <div>
                        <strong>Count:</strong>
                        <input type="number" name="itemId" value="@Model.ElementAt(i).Key" hidden>
                        <input type="number" name="count" value="@Model.ElementAt(i).Value">
                        <button type="submit" class="btn btn-custom-color">Update Count</button>
                    </div>
                </li>
                </form>
            }
        </ul>
        <div>
            <div>
                <strong>Total Price: @finalPrice</strong>
            </div>
            @*<a type="button" class="btn btn-custom-color" asp-controller="Purchase" name="unitPrice" value="@finalPrice" asp-action="Create" class="btn btn-sm btn-outline-secondary">Register Purchase</a>*@
            <form asp-controller="Purchase" asp-action="Create" method="post">
                <input type="hidden" name="unitPrice" value="@finalPrice">
                <button type="submit" class="btn btn-custom-color">Register Purchase</button>
            </form>
            <a type="button" class="btn btn-custom-color" asp-controller="PurchaseDetails" asp-action="CleanCart" class="btn btn-sm btn-outline-secondary">Clean</a>
        </div>
    </div>   
</body>
</html>