Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;
using WepPha2.Interfaces;
using WepPha2.Services;
using WepPha2.ViewModels;

namespace WepPha2.Controllers;

public class NotificationController : Controller
{
    private readonly IMedicineRepository _medicineRepository;
    private readonly NotificationService _notificationService;
    private readonly EmailObserver _emailObserver;
    private readonly SmsObserver _smsObserver;

    public NotificationController(
        IMedicineRepository medicineRepository,
        NotificationService notificationService,
        EmailObserver emailObserver,
        SmsObserver smsObserver)
    {
        _medicineRepository = medicineRepository;
        _notificationService = notificationService;
        _emailObserver = emailObserver;
        _smsObserver = smsObserver;
    }

    public async Task<IActionResult> Index()
    {
        return View("ChangeNotification");
    }
    [HttpPost]
    public async Task<IActionResult> ChangeNotification(ChoiseViewModel vm)
    {
        if (vm.EmailNotification)
            _notificationService.Attach(_emailObserver);
        else
            _notificationService.Detach(_emailObserver);
        if (vm.SmsNotification)
            _notificationService.Attach(_smsObserver);
        else
            _notificationService.Detach(_smsObserver);

        return View();
    }
    public async Task<IActionResult> Notificate()
    {
        var medicines = await _medicineRepository.GetAll();
        
        _notificationService.CheckMedicine(medicines);
        
        return RedirectToAction("Index", "Supplier");
    }

}

Views/Notification/ChangeNotification.cshtml
@model WepPha2.ViewModels.ChoiseViewModel

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/css/style_nav_bar.css" asp-append-version="true" />
</head>

<div class="container-sm bg-light" >
    <div class="row">
        <div class="col-md-12">
            <label>Choose Notification Type:</label>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <form asp-action="ChangeNotification" asp-controller="Notification" method="post">
                <div class="form-check">
                    <input id="email" type="checkbox" name="EmailNotification" asp-for="EmailNotification" class="form-check-input"/>
                    <label class="form-check-label" for="email">Email Notification</label>
                </div>

                <div class="form-check">
                    <input id="sms" type="checkbox" name="SmsNotification" asp-for="SmsNotification" class="form-check-input"/>
                    <label class="form-check-label" for="sms">SMS Notification</label>
                </div>

                <input type="submit" value="Choose" class="btn btn-success" />
            </form>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-12">
            <form asp-action="Notificate" asp-controller="Notification" method="get">
                <button type="submit" class="btn btn-success">Send Notification</button>
            </form>
        </div>
    </div>
</div>